# Generated by Django 5.1 on 2026-07-22 14:08

import django.core.validators
import django.db.models.deletion
import events.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=12, unique=True)),
                ('total_amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=16)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'credit account',
                'verbose_name_plural': 'credit accounts',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('MEMBER', 'Buyer / Seller'), ('EVALUATOR', 'Evaluator'), ('COURIER', 'Delivery partner')], db_index=True, default='MEMBER', max_length=16)),
                ('phone_number', models.CharField(blank=True, help_text='Used by couriers to reach you about a delivery.', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Enter a valid phone number: 7 to 15 digits, optionally starting with '+'.", regex='^\\+?[1-9]\\d{6,14}$')])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=events.models.avatar_upload_to)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('MOB_TAB', 'Mobiles and Tablets'), ('LAP_COMP', 'Laptops and Computers'), ('TV_MON', 'Televisions and Monitors'), ('HOME_APP', 'Home Appliances'), ('COMP_ACC', 'Computer Accessories'), ('GAM_CON', 'Gaming Consoles'), ('AUD_VID', 'Audio and Video Devices'), ('NET_DEV', 'Networking Devices'), ('STO_DEV', 'Storage Devices'), ('CAM_CORD', 'Cameras and Camcorders'), ('WEAR', 'Wearables'), ('OFF_EQUIP', 'Office Equipment'), ('IND_ELEC', 'Industrial Electronics'), ('MED_DEV', 'Medical Devices'), ('MISC', 'Miscellaneous Electronics')], db_index=True, default='MISC', max_length=16)),
                ('description', models.TextField(max_length=5000)),
                ('purchase_price', models.PositiveIntegerField(default=0, help_text='What the seller originally paid.')),
                ('purchased_on', models.DateField(blank=True, null=True)),
                ('listed_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(90)])),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting evaluation'), ('EVALUATING', 'Being evaluated'), ('LISTED', 'Listed for sale'), ('REJECTED', 'Rejected by evaluator'), ('SOLD', 'Sold')], db_index=True, default='PENDING', max_length=16)),
                ('evaluation_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('evaluation_notes', models.TextField(blank=True, max_length=2000)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='events.userprofile')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='events.order')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_item', to='events.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='events.userprofile')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='events.userprofile'),
        ),
        migrations.CreateModel(
            name='EvaluationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CLAIMED', 'In progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Released')], db_index=True, default='CLAIMED', max_length=16)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('claimed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_jobs', to='events.product')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_jobs', to='events.userprofile')),
            ],
            options={
                'verbose_name': 'evaluation job',
                'verbose_name_plural': 'evaluation jobs',
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('UNASSIGNED', 'Awaiting courier'), ('ASSIGNED', 'Courier assigned'), ('PICKED_UP', 'Picked up'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='UNASSIGNED', max_length=16)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='events.orderitem')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='events.userprofile')),
            ],
            options={
                'verbose_name': 'delivery',
                'verbose_name_plural': 'deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TOPUP', 'Top-up'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale payout'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Administrative adjustment')], db_index=True, max_length=16)),
                ('amount', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='events.creditaccount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='events.order')),
            ],
            options={
                'verbose_name': 'credit transaction',
                'verbose_name_plural': 'credit transactions',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['account', '-created_at'], name='events_cred_account_34baf2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='credit_transaction_amount_nonzero')],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_entries', to='events.product')),
            ],
            options={
                'verbose_name': 'cart item',
                'verbose_name_plural': 'cart items',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='cart_item_unique_per_user')],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=events.models.product_image_upload_to)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['position', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('product', 'position'), name='product_image_unique_position')],
            },
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role', 'is_available'], name='events_user_role_c86373_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'category'], name='events_prod_status_da2c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', 'status'], name='events_prod_seller__5d61c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('listed_price__gte', 1)), name='product_listed_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__lte', 90)), name='product_discount_max_90'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['seller'], name='events_orde_seller__75b8d4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', '-created_at'], name='events_orde_buyer_i_d6b9e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CLAIMED')), fields=('product',), name='evaluation_one_open_job_per_product'),
        ),
        migrations.AddConstraint(
            model_name='evaluationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CLAIMED')), fields=('evaluator',), name='evaluation_one_open_job_per_evaluator'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ASSIGNED', 'PICKED_UP'])), fields=('courier',), name='delivery_one_open_job_per_courier'),
        ),
    ]
