# Generated by Django 5.1.6 on 2025-03-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_product_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfull',
            name='userFull_phoneNumber',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
