# Generated by Django 5.1.6 on 2025-03-05 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_usercredits_user_alter_usercredits_usercredits_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredits',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercredits',
            name='userCredits_id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
    ]
