# Generated by Django 5.1.6 on 2025-03-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_usercredits_usercredits_id_alter_usercredits_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredits',
            name='userCredits_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
