# Generated by Django 5.1.6 on 2025-03-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_usercredits_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryguy',
            name='currently_working',
            field=models.IntegerField(default=0),
        ),
    ]
