# Generated by Django 5.1.6 on 2025-03-09 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_evaluatorguy_current_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatorjob',
            name='evaluatorJob_seller',
        ),
        migrations.RemoveField(
            model_name='evaluatorjob',
            name='evaluatorJob_status',
        ),
        migrations.AddField(
            model_name='evaluatorjob',
            name='evaluation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluatorjob',
            name='evaluatorGuy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.evaluatorguy'),
        ),
        migrations.AlterField(
            model_name='evaluatorjob',
            name='evaluatorJob_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evaluatorjob',
            name='evaluatorJob_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.product'),
        ),
        migrations.AlterModelTable(
            name='evaluatorjob',
            table='Evaluator Job',
        ),
    ]
