# Generated by Django 5.1.6 on 2025-03-10 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_evaluatorjob_evaluatorjob_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryguy',
            name='current_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dlv_product', to='events.product'),
        ),
    ]
