# Generated by Django 5.1.6 on 2025-03-12 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_deliveryguy_current_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryjob',
            name='deliveryJob_deliveryGuy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.deliveryguy'),
        ),
    ]
